### ISSUE TITLE
Exception occurs intermediately when using service broker.

### ISSUE THREAD

**Issue by cyclops1982** [K2NE/K2NEServiceBroker#26]
Hi,

We sometimes receive this exception:
Exception.Message: The type initializer for 'K2Field.K2NE.ServiceBroker.ServiceObjectBase' threw an exception.Exception.StackTrace: The type initializer for 'K2Field.K2NE.ServiceBroker.ServiceObjectBase' threw an exception.0 InnerException.Message: Access to the path 'environmentMutext' is denied.0 InnerException.StackTrace:
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

at System.Threading.Mutex.MutexTryCodeHelper.MutexTryCode(Object userData)

at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)

at System.Threading.Mutex.CreateMutexWithGuaranteedCleanup(Boolean initiallyOwned, String name, Boolean& createdNew, SECURITY_ATTRIBUTES secAttrs)

at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name, Boolean& createdNew, MutexSecurity mutexSecurity)

at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name, Boolean& createdNew)

at K2Field.K2NE.ServiceBroker.ServiceObjectBase..cctor() 

After investigation, it seems this exception occurs from the initialization of the Mutex that is used for the environment field locking.

**Comment by cyclops1982** [comment]
I've tried various pieces of code to create the mutex correctly, but i still can't get this to run without issues.

**Comment by cyclops1982** [comment]
Re-open this as the real issue has not been resolved. Need help for this one :(

**Comment by cyclops1982** [comment]
We managed to resolve this a while ago.
It turned out to be the ADO.NET query where permissions where needed. The initialization of that class (describe schema) did some queries against K2 and those would cause an error if it was not the right user performing it.
